version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
    - requirements: docs/source/requirements_readthedocs.txt
    - method: pip
      path: .

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub